apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
      - name: tasks
        image: logeshwarann/tasks-service:5493
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: service-config
---
apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  type: ClusterIP
  selector:
    app: tasks
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
